### ISSUE TITLE
Стоимость продажи недвижимости за квадратный метр 

### ISSUE THREAD

**Issue by AiratHalitov** [lenarsaitov/cianparser#10]
Можно добавить экспорт стоимости за квадрат в результаты парсинга? 
Может там есть такой параметр в таблице, но по умолчанию я не увидел. 

Если нельзя парсить сайта, то можно просто на лету посчитать (цену/площадь)

Я понимаю, что можно добавить столбец самому, но это важный параметр, который хотелось бы иметь по умолчанию. 

Спасибо! 

cianparcer v0.4.10

UPD: думаю в сдаче тоже имеет смысл выводить этот параметр 
типо **price_per_m2**

**Comment by lenarsaitov** [comment]
Да, пожалуй, можно добавить, оно информативно
Постараюсь, в ближайшее время

**Comment by AiratHalitov** [comment]
Кстати, цена за квадрат тоже с запятой должна быть, а не с точкой (на всякий случай напоминаю https://github.com/lenarsaitov/cianparser/issues/13 )
Хотя цифры после запятой там не особо важны, можно до целых вообще округлять, чтобы не париться.

**Comment by lenarsaitov** [comment]
Добавлено

Версия с обновлением 0.4.11
