### ISSUE TITLE
Фильтр "От собственника"

### ISSUE THREAD

**Issue by AiratHalitov** [lenarsaitov/cianparser#11]
Можно ли добавить фильтр "От собственника" в продажу и аренду? (очень нужно)

Ключ на циане: `is_by_homeowner=1`

**Comment by lenarsaitov** [comment]
Да, почему бы и нет, постараюсь в ближайшее время

**Comment by AiratHalitov** [comment]
Тогда было бы хорошо и в самой таблице иметь столбец Собственник (homeowner), чтобы по нему фильтровать.

**Comment by lenarsaitov** [comment]
Добавлен аргумент при запуске.
Плюс поле author_type. С соответствующими значения (описано в Readme)

Версия с обновлением 0.4.11
