### ISSUE TITLE
Failed exception:  could not convert string to float: '- 60'

### ISSUE THREAD

**Issue by golovanovaliza** [lenarsaitov/cianparser#14]
Добрый вечер! Наткнулась на ошибку, когда пыталась спарсить вот эту страницу, https://www.cian.ru/cat.php?engine_version=2&p=33&region=1&offer_type=flat&deal_type=rent&room2=1&with_neighbors=0&type=4

с помощью вот этого кода

 data = cianparser.parse(
    deal_type="rent_long",
    accommodation_type="flat",
    location="Москва",
    rooms=2,
    start_page=32,
    end_page=34,
    is_saving_csv=True,
    is_latin=False,
    is_express_mode=True,
)

Выдает: Failed exception:  could not convert string to float: '- 60'
Ending parse on 33 page...

Было бы круто, если б парсер просто игнорировал такие ошибки :) Спасибо!

**Comment by lenarsaitov** [comment]
Добрый вечер!
Спасибо за описанный момент
Посмотрю в ближайшее время

**Comment by lenarsaitov** [comment]
Данная ошибка исправлена
Плюс к тому же, теперь даже в любых других ошибках, будет переход на следующую страницу со списком объявлений
Версия с обновлением 0.4.11

**Comment by golovanovaliza** [comment]
Спасибо большое за оперативное обновление! 😊
