### ISSUE TITLE
Добавить парсинг домов

### ISSUE THREAD

**Issue by AiratHalitov** [lenarsaitov/cianparser#17]
Можно следующий на внедрение будет парсинг продажи домов?
```
accommodation_type="house"
deal_type="sale"
```

Сейчас он выдает: 
`Sorry. This functionality has not yet been implemented, but it is planned...`

Все остальные уже меньший приоритет имеют ("room", "house-part", "townhouse")

cianparser 0.4.11

**Comment by AiratHalitov** [comment]
Там еще надо будет собирать площадь участка (обычно в сотках).

Вот пример поиска:
https://sochi.cian.ru/cat.php?deal_type=sale&engine_version=2&is_by_homeowner=1&object_type%5B0%5D=1&offer_type=suburban&region=4998&with_neighbors=1

**Comment by lenarsaitov** [comment]
Да, почему бы и нет
Постараюсь добавить данный функционал в ближайших обновлениях

**Comment by lenarsaitov** [comment]
Добрый вечер!

Данный функционал был добавлен в недавних обновлениях, можно смотреть
Подробнее в [соответствующем описании](https://github.com/lenarsaitov/cianparser?tab=readme-ov-file#%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-get_suburban-%D1%81%D0%B1%D0%BE%D1%80-%D0%BE%D0%B1%D1%8A%D1%8F%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B9-%D0%B4%D0%BE%D0%BC%D0%BE%D0%B2%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BA%D0%BE%D0%B2%D1%82%D0%B0%D0%BD%D1%85%D0%B0%D1%83%D1%81%D0%B0%D0%B2-%D0%B8%D1%82%D0%BF)
