### ISSUE TITLE
Установка библиотеки

### ISSUE THREAD

**Issue by nickigami** [lenarsaitov/cianparser#20]
При скачивании библиотеки возникает ошибка. Не понимаю, я что-то делаю не так, или в чем-то другом проблема?
![image](https://user-images.githubusercontent.com/126822481/222551496-89cd9129-6d99-4928-9def-9b9c1a8faff6.png)

**Comment by lenarsaitov** [comment]
Добрый вечер!

Постараюсь разобраться в ближайшее время.

Верно ли (судя по скрину):
- система - windows
- версия python - 3.11
- команда - ``pip install cianparser ``

**Comment by nickigami** [comment]
> 

Добрый вечер! Да, все верно. Python - 3.11.2

**Comment by borisrulit** [comment]
Hi! 
Аналогичная проблема и у меня: Python 3.8.8

**Comment by nickigami** [comment]
> Hi! Аналогичная проблема и у меня: Python 3.8.8

Для меня проблема решилась установкой предыдущей версии библиотеки, но это все же костыль.

**Comment by ck-parabello** [comment]
Всем привет!
У кого то получилось запустить скрипт? Я установил версию 0.4.10 через терминал в пайчарме, но библиотека по прежнему не работает
![image](https://github.com/lenarsaitov/cianparser/assets/131950957/72e1f3d9-0fc0-48fd-84a8-c680c20cf432)

**Comment by Chewingus** [comment]
Та же проблема. 4.10 установился, 4.11 та же картина

**Comment by lenarsaitov** [comment]
Да, была проблема, связанная с кодировкой.

Подправил, в обновленной версии 0.4.12, можно смотреть
