### ISSUE TITLE
Не выгружает данные (адреса)

### ISSUE THREAD

**Issue by Spacelightpony** [lenarsaitov/cianparser#21]
Привет! К сожалению, парсер не выводит данные по адресам в городе Калуга, в тоже время, для Москвы выгружает.
![image](https://user-images.githubusercontent.com/127229021/223477383-f6a28287-c3e1-4ede-857c-92e914930746.png)

**Comment by lenarsaitov** [comment]
Добрый вечер!

Спасибо за предоставленный кейс. Подправил. Можно смотреть, начиная с версии **0.4.22**
