### ISSUE TITLE
Ошибка:  "IndexError: list index out of range"

### ISSUE THREAD

**Issue by habalov** [lenarsaitov/cianparser#25]
Добрый день. После изменения "deal_type" на "sale" появляется следующая ошибка: 

<img width="755" alt="Снимок экрана 2023-04-14 105119" src="https://user-images.githubusercontent.com/130651310/231980310-243efb23-decf-4822-83e0-2a1010d25e74.png">

Подскажите, пожалуйста, в чем может быть причина?

**Comment by NikitaStogniy** [comment]
Нет результатов парсенга скорее всего. Я увеличил верхний порог страниц до 50 и завелось

**Comment by lenarsaitov** [comment]
@habalov есть подозрение, что это было связано с BeautifulSoup

попробуйте последнюю (на данный момент) версию 0.4.13

в ней я внес исправление
