### ISSUE TITLE
Ошибка TypeError 

### ISSUE THREAD

**Issue by MaximScherbatov** [lenarsaitov/cianparser#26]
Добрый день! В версии 0.4.10 (0.4.11 не устанавливается) возникает ошибка 
TypeError: parse() got an unexpected keyword argument 'is_by_homeowner'

Парсер удалось запустить закомментировав атрибут is_by_homeowner

**Comment by Geligord** [comment]
Та же самая ошибка. Хотел обойти ошибку через тип автора объявления, но не получилось
TypeError: parse() got an unexpected keyword argument 'author_type'

**Comment by lenarsaitov** [comment]
Добрый день!

Это связано с тем, что подобный аргумент появился лишь в 0.4.11 версии

Установите версию 0.4.12, в ней решена проблема, связанная с кодировкой, из-за которой (как я предполагаю), связана ошибка установки
