### ISSUE TITLE
Мало объектов в выдаче

### ISSUE THREAD

**Issue by Chewingus** [lenarsaitov/cianparser#28]
Спасибо за библиотеку.
Столкнулся со следующим.
Мой запрос 
parse_df = cianparser.parse(
    deal_type="rent_long",
    accommodation_type="flat", 
    location="Москва", 
    rooms=(2, 3),
    is_express_mode=True
)
версия парсера 0.4.10. 
По идее он должен выдать  28*54=1512 объектов, а выдал 280. Если забить в циане москву, аренда, квартира 2 и 3 комнатные то даже выбрав только районы внутри мкада выдача показывает 5852 объявления. То есть 1512 объектов там точно есть. В чем может быть проблема?

P.S. Есть ещё одна проблема. Почему то в этих 280 объявлениях подавляющее количество с весьма высокой стоимостью аренды и преимущество в югозападных районах. Полагаю выдача циана как то отсортирована так что в первых позициях попадаются дорогие предложения? Можно как то на это влиять?

P.S.S. Можно считать что вопрос закрыт. Добавил end_page=100 мне выдало все 100 страниц. В описании написано что максимум 54 и 100 по умолчанию. Видимо в версии 4.10 это было не так.

**Comment by lenarsaitov** [comment]
Рад, что библиотека оказалась полезной

Попробуйте последнюю, на данный момент, версию, 0.4.12. При ее использовании подобные проблемы встречаться не должны
