### ISSUE TITLE
Дупликаты в выдаче

### ISSUE THREAD

**Issue by Chewingus** [lenarsaitov/cianparser#29]
из 2797 объектов 1319 полных дубликата без учета оригинала вплоть до ссылки на объявление. Причем это не последние 1319 объектов. Они разбросаны по датасету. С чем это может быть связано?

**Comment by lenarsaitov** [comment]
это связано с тем, что сайт выдает списки с объявлениями лишь до 54 страницы включительно

далее при попытке перейти на 55 страницу, нас перебрасывает уже на первую, и всё идет по новой

в описании к проекту я указывал на подобное, хотя, пожалуй, не совсем явно..

https://github.com/lenarsaitov/cianparser#%D0%BE%D0%B3%D1%80%D0%B0%D0%BD%D0%B8%D1%87%D0%B5%D0%BD%D0%B8%D1%8F

**Comment by Chewingus** [comment]
Тогда у 2797 объектов должно быть 1285 дубликатов а не 1319?

**Comment by lenarsaitov** [comment]
хмм, интересно, постараюсь изучить подобный момент в ближайшее время

**Comment by lenarsaitov** [comment]
но а так, начиная с 0.4.11, имеется функционал определения переброски страницы на иную позицию

**Comment by Chewingus** [comment]
> хмм, интересно, постараюсь изучить подобный момент в ближайшее время.
> 
> вполне возможно, что это связано с показом рекламных объявлений

А рекламные тоже в выдаче есть?

**Comment by lenarsaitov** [comment]
да, как я помню, подобные имеются, хоть и в небольшом количеств

некоторые из объявлений могут повторятся на разных страницах

их я и именную рекламными, хотя как таковой особой маркировки на сайте нет

**Comment by lenarsaitov** [comment]
@Chewingus можно ли считать проблему решенной?

**Comment by Chewingus** [comment]
Да, спасибо
