### ISSUE TITLE
offer = sale ?

### ISSUE THREAD

**Issue by pavel555ru** [lenarsaitov/cianparser#3]
Какие планы по добавлению offer = sale?

**Comment by AiratHalitov** [comment]
+1

**Comment by lenarsaitov** [comment]
Добрый день!
Данный функционал сегодня был добавлен вместе с существенным обновлением всего проекта.
Буду рад обратной связи, а также звездочкам к проекту (это приятно).

**Comment by AiratHalitov** [comment]
Спасибо за обновление! Обязательно проверю в ближайшее время

**Comment by AiratHalitov** [comment]
Всё работает!
