### ISSUE TITLE
Формирует ссылку, но обьявлений 0

### ISSUE THREAD

**Issue by Psymtb** [lenarsaitov/cianparser#36]
Добрый день!

Кейс: 
1. Запускаю 
import cianparser

data = cianparser.parse(
    deal_type="sale", 
    accommodation_type="flat",
    location="Москва",
    rooms=(1),
    start_page=1,
    end_page=54,
    is_saving_csv=True,
    
)

print(data[0])

2. Скрипт сгенерил ссылку. По которой предложения, очевидно, есть 
3. The page from which the collection of information begins: 
 https://cian.ru/cat.php?engine_version=2&p=1&region=1&offer_type=flat&deal_type=sale&room1=1&with_neighbors=0

3. Рапортует, что предложений нет. Как следствие, средний прайс - ноль. 
The collection of information from the pages with list of announcements is completed
Total number of parsed announcements: 0. Average price: 0 rub

Есть подозрение, что что-то изменилось у циана в части пагинатора.  
Вчера работало. Пытаюсь прикрутить фронт с аналитикой для домашнего использования. 

Дополнительно хотел сказать автору спасибо за реализацию и подробное описание, которое понятно даже джуну)

**Comment by Psymtb** [comment]
Не актуально
![image](https://github.com/lenarsaitov/cianparser/assets/156030853/14255fe3-1732-4e53-a45a-e70300684db5)

**Comment by Kent4r** [comment]
Обоюдно🤙
