### ISSUE TITLE
object_type и demolished_in_moscow_programm

### ISSUE THREAD

**Issue by Psymtb** [lenarsaitov/cianparser#37]
Приветствую! 
Пытаюсь передать additional_settings = "object_type[0]": 1 (в ссылке он "object_type%5B0%5D=1") - признак вторички/новостройки.  Попробовал разные вариации. 
Либо я что-то делаю не так, либо оно и не должно было работать. 
В readme вроде заявлен как новое. Буду очень признателен, если добавите. 

Хочу поблагодарить Вас за столь полезную библиотеку! Очень помогает в выборе собственного жилья.

**Comment by Psymtb** [comment]
Для инфо остальным пользователям: 
Пока можно ограничить годом постройки

**Comment by lenarsaitov** [comment]
Добрый день!

Рад, что библиотека оказалась полезной
Вы правы, на тот момент данная настройка для поиска не была реализована в фунцкционале
Добавил в версии 1.0.0, в котором проект был существенным образом проработан (прежде всего в отрефакторен, но не только)
Прошу обновить

Пример запуска (object_type, возможные значения "new" и "secondary"):
```
import cianparser

moscow_parser = cianparser.CianParser(location="Москва")
data = moscow_parser.get_flats(
    deal_type="sale",
    rooms=(1, 2),
    with_saving_csv=True,
    with_extra_data=True,
    additional_settings={"object_type": "new", "start_page": 1, "end_page": 1},
)

print(data[0])

```
