### ISSUE TITLE
Не получается спарсить, с впн тоже. наверное проблема в заглушке, что есть на 5 секунд на сайте.

### ISSUE THREAD

**Issue by kargintima** [lenarsaitov/cianparser#6]
Start collecting information from pages..
503 Server Error: Service Temporarily Unavailable for url: https://cian.ru/cat.php?deal_type=rent&engine_version=2&p=1&region=4588&offer_type=flat&type=4
Dont exist this 1 page.. Ending parse

Есть идеи у кого?

**Comment by lenarsaitov** [comment]
Постараюсь посмотреть на днях

**Comment by q00Dree** [comment]
Аналогичная ошибка, есть обновления по этому вопросу?

**Comment by vbaryshev** [comment]
Аналогично

**Comment by lenarsaitov** [comment]
Проблема была связана с Cloudflare anti-bot page

При помощи библиотеки cloudscraper удалось обойти данное ограничение
https://github.com/VeNoMouS/cloudscraper

Выпустил соответствующее обновление
