### ISSUE TITLE
[Errno 22]

### ISSUE THREAD

**Issue by Pipisoid23** [lenarsaitov/cianparser#7]
Здравствуйте!
Возникает такая проблема, не знаю в чём дело:
Failed exception:  [Errno 22] Invalid argument: 'C:/Users/Pipisoid/PycharmProjects/pythonProject/venv/cian_parsing_result_sale_1_1_moskva_2023-02-04 11:12:45.155959.csv'

Подскажите, пожалуйста.

**Comment by lenarsaitov** [comment]
Добрый день!
Попробуйте обновить библиотеку, выпустил 0.4.7 версию с исправлением (и пожалуйста отпишитесь, сам протестировать не могу, тк не имею windows)

**Comment by Pipisoid23** [comment]
> Добрый день! Попробуйте обновить библиотеку, выпустил 0.4.7 версию с исправлением (и пожалуйста отпишитесь, сам протестировать не могу, тк не имею windows)

Слэши в пути к файлу изменились, но ошибка осталась :(
Failed exception:  [Errno 22] Invalid argument: 'C:\\Users\\Pipisoid\\PycharmProjects\\pythonProject\\venv\\cian_parsing_result_sale_1_1_moskva_2023-02-04 14:11:57.232096.csv'

**Comment by lenarsaitov** [comment]
Хмм, странно

Можете написать мне в телегу? Хотел бы скооперироваться с вами по этой проблеме, если вы не против (тк, опять таки, у меня нету винды)

@lenarsaitov

**Comment by Pipisoid23** [comment]
Да, конечно, написала

**Comment by Pipisoid23** [comment]
После обновления 0.4.8 всё работает на Windows. Огромное спасибо @lenarsaitov за библиотеку и за быструю помощь!
