### ISSUE TITLE
парсер не работает после обновления 

### ISSUE THREAD

**Issue by golovanovaliza** [lenarsaitov/cianparser#8]
Привет! Спасибо за код, я его использовала в своем проекте. Я работаю на mac os, все исправно собиралось до твоего обновления несколько часов назад. Я исключила возможность блокировки на сайте, добавив код для регулярного обновления IP, это не помогло. Возможно, дело в обновлениях. Но я проверила все прошлые версии через pip install -U cianparser=='0.4.9' вплоть до 0.4.7, все равно ничего не собирается. У кого-то есть похожие проблемы?

**Comment by lenarsaitov** [comment]
Добрый вечер!

Да, тоже заметил данную проблему
Оказалось, случайно добавил ограничение на версию Python, от 3.9

Данное ограничение, и выкатил обновление попробуйте версию 0.4.10

**Comment by AiratHalitov** [comment]
У меня работает. 
Linux Mint 21
cianparser v0.4.10
python3 v3.10.6

И аренда, и продажа

**Comment by golovanovaliza** [comment]
Спасибо, все работает!

**Comment by lenarsaitov** [comment]
Рад, что всё получилось
