### ISSUE TITLE
Парсинг адреса (Дома)

### ISSUE THREAD

**Issue by tmvnn** [lenarsaitov/cianparser#9]
Здравствуйте!
Большое спасибо за софт! 
Планируете ли добавлять парсинг номера дома (точный адрес)? Очень хотелось бы склеить по адресу стоимость квартиры в доме и цену аренды квартиры для покупки оптимальной квартиры по соотношение цены квартиры к цене аренды:) Был бы очень признателен 🙏🏻
По идее по аналогии с улицей можно быстро дописать, но не знаком с питоном:/

**Comment by lenarsaitov** [comment]
Добрый вечер!
Да, пожалуй стоит, постараюсь в ближайшее время

**Comment by lenarsaitov** [comment]
Добрый вечер!

Соотвествующий функционал был добавлен в версии _0.4.23_. 
Поле **_house_number_**.
